### ISSUE TITLE
Using map config incorrectly

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs-react#2]
This adds a map config for an alternative version of inline-cache [here](https://github.com/donejs/donejs-react/commit/8f29523e7c93837b3dfaebaa13888b475df120bc#diff-4c369dba87d04d9dd75de0ae4b320c64L27).

What you really want is this:

```js
map: {
  'can-connect/data/inline-cache/inline-cache': 'can-react/extensions/can-connect-inline-cache'
}
```

If this doesn't work for some reason let me know.  You could also keep what you have but use a `paths` instead of `map`.

**Comment by DesignByOnyx** [comment]
The suggested change works for me.

**Comment by Alfredo-Delgado** [comment]
resolved by https://github.com/donejs/donejs-react/commit/b13b243434bef4522f9c21993358521c1ece6193#diff-4c369dba87d04d9dd75de0ae4b320c64L17
